pipeline {
    agent any
    stages {
        stage('Restart') {
            steps {
                sh '''
                pkill -f node || true
                cd /opt/app/node_app
                nohup node server.js > app.log 2>&1 &
                '''
            }
        }
    }
}
