pipeline {
    agent any

    environment {
        APP_REPO = 'https://github.com/vijayqadevkraft/webapplication-repo.git'
        SCRIPT_REPO = 'https://github.com/vijayqadevkraft/script-repo.git'
    }

    stages {

        stage('Checkout Pipeline Repo') {
            steps {
                echo "✅ Jenkinsfile loaded from pipeline-repo (main branch)"
            }
        }

        stage('Clone Application Repo') {
            steps {
                dir('app') {
                    git branch: 'main', url: "${APP_REPO}"
                }
            }
        }

        stage('Clone Script Repo') {
            steps {
                dir('script') {
                    git branch: 'main', url: "${SCRIPT_REPO}"
                }
            }
        }

        stage('Build') {
            steps {
                echo "⚙️ No build required for static HTML application"
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                echo "🚀 Starting deployment..."

                # Give execute permission
                chmod +x script/simple-index-html-script/deploy.sh

                # Run deployment script
                ./script/simple-index-html-script/deploy.sh
                '''
            }
        }
    }

    post {
        success {
            echo "🎉 Deployment Successful"
        }
        failure {
            echo "❌ Deployment Failed"
        }
    }
}
