pipeline {
    agent any

    environment {
        APP_REPO = 'https://github.com/vijayqadevkraft/webapplication-repo.git'
        SCRIPT_REPO = 'https://github.com/vijayqadevkraft/script-repo.git'
    }

    stages {

        stage('Checkout Pipeline Repo') {
            steps {
                echo "Jenkinsfile loaded from pipeline-repo"
            }
        }

        stage('Clone Application Repo') {
            steps {
                dir('app') {
                    git branch: 'feature/simple-fullstack-setup-15135607', 
                url: "${APP_REPO}"
                }
            }
        }

        stage('Clone Script Repo') {
            steps {
                dir('script') {
                    git branch: 'main', url: "${SCRIPT_REPO}"
                }
            }
        }

        stage('Build') {
            steps {
                echo "No build required for static HTML app"
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                echo "Starting deployment..."
                
                chmod +x script/simple-index-html-script/deploy.sh
                
                ./script/simple-index-html-script/deploy.sh
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful"
        }
        failure {
            echo "❌ Deployment Failed"
        }
    }
}
